### ISSUE TITLE
[Question] Is it possible for you to port it to the FrankerFaceZ addon?

### ISSUE THREAD

**Issue by Waynekosimoto** [chylex/Transparent-Twitch-Chat#11]
Recently the [FrankerFaceZ](https://github.com/FrankerFaceZ/FrankerFaceZ) extension added support for addons and I am wondering if it is possible to port it over to the extension. Currently there are 2 addons, [The FFZ Add-on Pack](https://chrome.google.com/webstore/detail/the-ffz-add-on-pack/aiimboljphncldaakcnapfolgnjonlea?hl=en-US) and [The FFZ Enhancing Addon-On](https://chrome.google.com/webstore/detail/the-ffz-enhancing-add-on/dpjloclnedokpfjlolaebpbaclbdigon?hl=en-US). I don't know how the system works but I know he recently made an official tab for addons. The extension is pretty legit.

**Comment by chylex** [comment]
TTC used to work with FFZ (and BTTV) until Twitch completely redesigned their chat systems several times and broke all other addons, so I updated TTC and removed any addon compatibility because the other addons weren't updated at the time. I'll keep this in mind.

**Comment by chylex** [comment]
Is there anything specific causing issues with both installed at the same time? Some options that are shared (like chat width) may only work if you disable the option in FFZ and use TTC's one.

**Comment by chylex** [comment]
Closing due to no response. Reopen with more information if there's still an issue.
