### ISSUE TITLE
it's broken again

### ISSUE THREAD

**Issue by TwitchKappa** [chylex/Transparent-Twitch-Chat#24]
Twitch.tv changed something and broke it again. tested on clean Fox profile with violent monkey. thank you

**Comment by chylex** [comment]
Can't see any major issues, can you send a screenshot? Maybe Twitch hasn't pushed the updated to my account/region yet.

**Comment by TwitchKappa** [comment]
tried to attach a screenshot to this post.
![waterfox_2018-11-17_09-11-08](https://user-images.githubusercontent.com/23336873/48662107-ef6a4a00-ea4a-11e8-95be-1a40fbb81af5.jpg)

**Comment by TwitchKappa** [comment]
Update: it appears to be working on 1 of my chrome profiles, but not another one. still not sure what exactly is causing it.

Update 2: I was able to break the chrome profile that was working by deleting all cookies and re-logging on. There may be a preference or setting in the cookies that is serving up different versions of the webpage. Try backing up your profile, deleting your cookies, And relogging.

Also even when it is working the chrome version is not fully filling out the screen While the browser is in full screen and theater mode, while there is a user logged in To twitch.tv. This bug has happened before. screenshot attached.
![chrome_2018-11-17_09-47-22](https://user-images.githubusercontent.com/23336873/48662533-42df9680-ea51-11e8-9736-39620e8927c4.jpg)

**Comment by chylex** [comment]
I see the issue happening in incognito, I'll look into it. But with fullscreen mode, TTC shouldn't be doing anything at all.

**Comment by chylex** [comment]
Closed in https://github.com/chylex/Transparent-Twitch-Chat/commit/2cdf859ebe4f1e48a47b16a029642d4789fbd39b
