### ISSUE TITLE
stopped working again, same issue as a few days ago

### ISSUE THREAD

**Issue by TwitchKappa** [chylex/Transparent-Twitch-Chat#25]
hello sorry to bother you again, but it has stopped working in the same way as last time as of a couple days ago. I waited a few days to see if it would get fixed on its own

not sure if you still want screenshots, it's the same issue as last time.

**Comment by chylex** [comment]
Yea, for some reason they keep changing it, I see some features (like turning off sub badges) break and then start working again, different every week. I'll fix it tomorrow.
