### ISSUE TITLE
Not all icons before names can be hidden

### ISSUE THREAD

**Issue by SmashRocket** [chylex/Transparent-Twitch-Chat#27]
Still seeying some clutter before names like Moderator and Power Cliper. Would like an option to clear all 'Clutter" not just those badges.

**Comment by chylex** [comment]
Reducing Badge Opacity to 0% is supposed to hide all badges, but it looks like the option is broken atm.

**Comment by chylex** [comment]
Twitch updated and Badge Opacity seems to be working again.
