### ISSUE TITLE
No longer working on VODS

### ISSUE THREAD

**Issue by StoneColeQ** [chylex/Transparent-Twitch-Chat#29]
Seems twitched changed something with vod chat so it now longer works. It was about a week ago. FFZ's transparent chat doesn't work either. Still works on livestreams (though you have to disable/reenable).

**Comment by chylex** [comment]
Nothing has changed on my end so I can't fix it until they roll out the changes to my account.

**Comment by chylex** [comment]
I still haven't seen any updates to Twitch that break transparency in VODs, is it still broken on your end?

**Comment by dsetareh** [comment]
FFZ can conflict with this script in vods, blocking the color_normalizer css load fixed it
