### ISSUE TITLE
Feature request - 800px

### ISSUE THREAD

**Issue by nazsol** [chylex/Transparent-Twitch-Chat#31]
Is it possible to make chat width 800px? i have an ultrawide and there is a black column in between video and chat, if it's easy to do then i would like to use that, otherwise no biggie and ignore this

 ![canvas](https://user-images.githubusercontent.com/40800362/134994213-cb5d0875-2b93-43e0-91db-e8c116423ad0.png)
.

**Comment by chylex** [comment]
For a quick fix, you can edit the script in your userscript manager, and change this line: https://github.com/chylex/Transparent-Twitch-Chat/blob/b9d2cd736bd9092c1334e15643b56739eb0118ea/dist/TransparentTwitchChat.user.js#L464

change the number after `max` to however high you want the slider to go, for example:
```js
${generateSlider("Chat Width", "chatWidth", { min: 250, max: 800, step: 25, wait: 500, text: "px" })}
```

here's a difference view to make the change clearer:
```diff
- ${generateSlider("Chat Width", "chatWidth", { min: 250, max: 600, step: 25, wait: 500, text: "px" })}
+ ${generateSlider("Chat Width", "chatWidth", { min: 250, max: 800, step: 25, wait: 500, text: "px" })}
                                                               ^
```

**Comment by nazsol** [comment]
Awesome thanks!
