### ISSUE TITLE
white bar on side of the chat screen after reloading

### ISSUE THREAD

**Issue by TwitchKappa** [chylex/Transparent-Twitch-Chat#5]
I'm using the latest version of Firefox for this add-on. When loading a stream for the 1st time the display looks fine,, but after reloading the page by pressing F5 there is what looks like a scrollbar artifact. This artifact doesn't go away unless I back out to the following page and then click on the stream again.I

I believe what is happening is that the chat scrollbar is reverting back to the default state that is opaque and not styled.thanks again for your help.
![waterfox_2017-09-10_19-23-42](https://user-images.githubusercontent.com/23336873/30253967-343c0796-965e-11e7-9b12-e195c2b3385d.jpg)

**Comment by chylex** [comment]
1. Any other addons? Try it without them and see if the issue still happens
2. It looks like you're zoomed in; can you try using `View -> Zoom -> Zoom Text Only` in Firefox to make sure only text size is changed? These kinds of artifacts sometimes happen with zoom in general

**Comment by TwitchKappa** [comment]
I believe I fixed the problem by switching my Firefox script add-on from Grease monkey to tamper monkey. Thank you
