### ISSUE TITLE
feature suggestion to alternate transparency levels between lines

### ISSUE THREAD

**Issue by TwitchKappa** [chylex/Transparent-Twitch-Chat#6]
I really like the better twitch TV feature called split chat which alters the colours between each chat message to make messages more easily distinguishable.you could do something similar by making each alternating chat message a slightly different level of transparency.
thank you for your time and consideration

**Comment by chylex** [comment]
BTTV should work fine with TTC, are there any issues with this particular feature?

**Comment by TwitchKappa** [comment]
I am saying I would like to see a new feature that replicates  split chat except with transparencies. see this photo for the example, it's using a different twitch chat overlay add-on than yours.

Also being able to export the settings to a file would be great..
![waterfox_2017-09-14_16-34-46](https://user-images.githubusercontent.com/23336873/30454787-89f9f804-996b-11e7-8b92-837b384e2c9b.jpg)

**Comment by chylex** [comment]
I can look into that, but it's not an extremely simple issue as the transparency is set for the chat background and does not affect text or individual messages. Also had a request for text transparency, so I'd probably deal with both at the same time, just don't know when.

**Comment by chylex** [comment]
Not planning to add this, sorry. You could probably write a custom style for this and load it into a user style manager like Stylus.
