### ISSUE TITLE
 new twitch URL compatibility

### ISSUE THREAD

**Issue by TwitchKappa** [chylex/Transparent-Twitch-Chat#7]
as of a couple hours ago Twitch is now using the URL go.twitch.tv. this has unfortunately caused the add-on to stop working even when the new URL is added as a custom include

okay apparently this is the twitch beta site which can be disabled but I am guessing they will switch everyone over to it eventually so you will probably have to address it eventually.

thank you for your help

**Comment by chylex** [comment]
Known issue, an update will be out whenever I have time to update it. That might be once Twitch moves everyone onto beta though, since the update will consequently break compatibility with the legacy site and I'd rather wait in case Twitch ends up breaking the beta site.

**Comment by TwitchKappa** [comment]
twitch just forced everyone onto the new site layout and there is no opt out anymore. Better twitch TV is also broken although I don't know how much it affects your add-on.

**Comment by chylex** [comment]
I'll update TTC in a few days.

**Comment by TwitchKappa** [comment]
Okay thank you very much Twitch.tv is just not the same without your add-on
